louvre_app_home:
    path:     /
    defaults: { _controller: LOUVREAppBundle:App:home }

louvre_app_command:
    path:     /commande
    defaults: { _controller: LOUVREAppBundle:App:command }
    
louvre_app_commandtickets:
    path:     /commande/{bookingCode}
    defaults: { _controller: LOUVREAppBundle:App:commandTickets }
    requirements:
        orderNumber: "([A-Z])(\d+)(LOUVRE)(\d+)"

louvre_app_summary:
    path:     /résumé/{bookingCode}
    defaults: { _controller: LOUVREAppBundle:App:summary }
    requirements:
        orderNumber: "([A-Z])(\d+)(LOUVRE)(\d+)"

louvre_paypal_payment_prepare:
    path:     /paypal/{bookingCode}
    defaults: { _controller: LOUVREAppBundle:Payment:preparePaypalExpressCheckoutPayment }

louvre_stripe_payment_prepare:
    path:     /stripe/{bookingCode}
    defaults: { _controller: LOUVREAppBundle:Payment:prepareStripeJsPayment }

louvre_payment_done:
    path:     /done
    defaults: { _controller: LOUVREAppBundle:Payment:captureDone }

louvre_after_payment:
    path:     /confirmation
    defaults: { _controller: LOUVREAppBundle:App:afterPayment }
