louvre_app_home:
    path:     /
    defaults: { _controller: LOUVREAppBundle:App:home }

louvre_app_command:
    path:     /commande
    defaults: { _controller: LOUVREAppBundle:App:command }
    
louvre_app_commandtickets:
    path:     /commande/{bookingCode}
    defaults: { _controller: LOUVREAppBundle:App:commandTickets }
    requirements:
        orderNumber: "([A-Z])(\d+)(LOUVRE)(\d+)"