services:
    louvre_app.toddler:
        class: LOUVRE\AppBundle\Rate\LOUVREToddlerRate

    louvre_app.child:
        class: LOUVRE\AppBundle\Rate\LOUVREChildRate
        
    louvre_app.senior:
        class: LOUVRE\AppBundle\Rate\LOUVRESeniorRate
        
    louvre_app.family:
        class: LOUVRE\AppBundle\Rate\LOUVREFamilyRate
        
    louvre_app.half:
        class: LOUVRE\AppBundle\Ticket\LOUVREHalfTicket
        
    louvre_app.thousand:
        class: LOUVRE\AppBundle\Ticket\LOUVREThousandTickets
    
    louvre_app.ordernumber:
        class: LOUVRE\AppBundle\Order\LOUVREOrderNumber