services:
    louvre_app.toddler:
        class: LOUVRE\AppBundle\Ticket\LOUVREToddlerPrice

    louvre_app.child:
        class: LOUVRE\AppBundle\Ticket\LOUVREChildPrice
        
    louvre_app.senior:
        class: LOUVRE\AppBundle\Ticket\LOUVRESeniorPrice
        
    louvre_app.family:
        class: LOUVRE\AppBundle\Ticket\LOUVREFamilyPrice
        arguments: ['@louvre_app.child']
        
    louvre_app.half:
        class: LOUVRE\AppBundle\Ticket\LOUVREHalfTicket

    louvre_app.thousand:
        class: LOUVRE\AppBundle\Ticket\LOUVREThousandTickets
        arguments: ['@doctrine.orm.entity_manager']

    louvre_app.getprice:
        class: LOUVRE\AppBundle\Ticket\LOUVREGetPrice
        arguments: ['@louvre_app.toddler', '@louvre_app.child', '@louvre_app.senior']

    louvre_app.getname:
        class: LOUVRE\AppBundle\Ticket\LOUVRETicketsName
        arguments: ['@louvre_app.toddler', '@louvre_app.child', '@louvre_app.senior']
    
    louvre_app.bookingcode:
        class: LOUVRE\AppBundle\Command\LOUVREBookingCode
