louvre_app:
    resource: "@LOUVREAppBundle/Resources/config/routing.yml"
    prefix:   /

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"