<?php

namespace LOUVRE\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTicketRepository extends EntityRepository
{
}
